Changed to SHA256 #138
OpenChemistry/openchemistry pull request #147
Opened 2024-12-17 18:47 UTC by peach280

Changed MD5 hashes to SHA256. Please review and suggest improvements.

2024-12-19 17:14 UTC, ghutchis commented
I'll take a look later today or tomorrow -- sorry that I've been busy with a few other things.

2024-12-20 12:23 UTC, Krzmbrzl requested changes

2024-12-20 12:23 UTC, Krzmbrzl commented on cmake/CMakeCache.txt
This file should bot be part of the PR

2024-12-20 12:23 UTC, Krzmbrzl commented on cmake/CMakeFiles/3.31.2/CMakeSystem.cmake
This file should bot be part of the PR

2024-12-20 12:23 UTC, Krzmbrzl commented on cmake/CMakeFiles/CMakeConfigureLog.yaml
This file should bot be part of the PR

2024-12-20 12:23 UTC, Krzmbrzl commented on cmake/CMakeFiles/cmake.check_cache
This file should bot be part of the PR

2024-12-20 12:36 UTC, peach280 commented
I have updated the changes please review.

2024-12-20 13:59 UTC, Krzmbrzl approved these changes
LGTM, for what that's worth

2024-12-22 14:32 UTC, peach280 commented
Is there any update about my PR?

2024-12-30 18:22 UTC, peach280 commented
@ghutchis any updates on my PR?

2025-01-03 18:17 UTC, peach280 commented
@Krzmbrzl  @ghutchis Are there any further improvements which can de done from my side in my pull request?

2025-01-03 18:37 UTC, Krzmbrzl commented
Please stop spamming this PR. I don't have anything to say in this repo (I'm not a maintainer) and ghutchis clearly doesn't have any time at the moment or else he would have responded to your previous ping.

2025-01-05 20:12 UTC, ghutchis commented
LGTM - I'm just not going to change anything right before we release 1.100. Call me superstitious. I'd guess that we release 1.100 sometime this coming week - waiting to hear back about a Windows bug.

2025-09-13 19:00 UTC, merged